version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: cron
      cronjob: 0 8 * * SAT
      timezone: Canada/Pacific
    versioning-strategy: increase-if-necessary
    groups:
      lint:
        patterns:
          - '@eslint/eslintrc'
          - '@typescript-eslint/*'
          - eslint
          - eslint-config-prettier
          - eslint-plugin-prettier
          - prettier

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: cron
      cronjob: 0 8 * * SAT
      timezone: Canada/Pacific
